In [22]:
import pandas as pd 
import numpy as np
import scipy.stats as st
import scipy.optimize as opt
import sklearn.linear_model as lm



In [2]:
np.linspace?

In [3]:
#Week 1 quiz

x = [0.18, -1.54, 0.42, 0.95]
w = [2, 1, 3, 1]

In [15]:
print np.array(x)*np.array(w)
print [a*b for a,b in zip(x,w)]

[ 0.36 -1.54  1.26  0.95]
[0.36, -1.54, 1.26, 0.95]


In [16]:
def func(xdata, ydata):
    return ydata - xdata

In [17]:
func(w, np.array(x)*np.array(w))

array([-1.64, -2.54, -1.74, -0.05])

In [20]:
opt.leastsq(func, args=(w, x0, np.array(x)*np.array(w)))

NameError: name 'x0' is not defined

In [42]:
#Fit regression through the data 

#Data
x_reg = np.array([0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42])
y_reg = np.array([1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05])



array([[ 1.39,  0.72,  1.55,  0.48,  1.19, -1.59,  1.23, -0.65,  1.49,
         0.05]])

In [47]:
#TO DO with smf OLS
regr = lm.LinearRegression()
regr.fit(x_reg.reshape(10,1), y_reg.reshape(10,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [50]:
print 'Coefficients: \n' + str(regr.coef_)


Coefficients: 
[[-1.71284595]]
